engines:
  eslint:
    enabled: true
  stylelint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 70

ratings:
   paths:
    - "**.js"
    - "**.jsx"
    - "**.css"

exclude_paths:
- static/**/*
