backend:
  name: git-gateway
  branch: gatsby-refactor

media_folder: static/images
public_folder: /images

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: 'templateKey', widget: "hidden", default: "project-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Publication date", name: "publicationDate", widget: "date"}
      - {label: "Tasks", name: "tasks", widget: "markdown"}
      - {label: "Mandate", name: "mandate", widget: "markdown"}
      - {label: "Collaborators", name: "collaborators", widget: "list"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Stack", name: "stack", widget: "list"}
